name: BukkitTTY
main: net.frazew.bukkittty.BukkitTTY
version: 0.0.2
commands:
   shell:
      description: Lance une commande shell dans un repertoire
      usage: /<command> command [--shellDir/home/.]
      permission: overviewer.shell
      permission-message: You don't have <permission>